# Generated by Django 3.2.4 on 2021-07-15 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dhcp_static',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mac', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netmask', models.CharField(max_length=15)),
                ('ip_network', models.CharField(max_length=15)),
                ('ip_broadcast', models.CharField(max_length=15)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dhcp_Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ip_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('hostname', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipam.subnet')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.SET(''), to='ipam.OS')),
            ],
        ),
    ]
